export const AUTH_LOGGING_IN = 'AUTH_LOGGING_IN';
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_FAILURE = 'AUTH_FAILURE';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGGING_OUT = 'AUTH_LOGGING_OUT';

export const SEARCH_FOR_LOCALITY = 'SEARCH_FOR_LOCALITY';
export const LOCALITY_SEARCH_RESULTS = 'LOCALITY_SEARCH_RESULTS';
